import { Space_Grotesk } from "next/font/google";
import Header from "@/components/Header/";
import Footer from "@/components/Footer";


const space = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>

  );
}
